let questions = [
  {
    question: "What is the name of the most famous Pokemon?",
    answer1: "Pikachu",
    answer2: "Charizard",
    answer3: "Blastoise",
    answer4: "Venusaur",
    right_answer: 1,
    image: "./img/pikachu.jpg",
  },
  {
    question: "Which real time strategy game was released in 1999?",
    answer1: "Starcraft 2",
    answer2: "Baldurs Gate 3",
    answer3: "Age of Empires II",
    answer4: "Cyberpunk 2077",
    right_answer: 3,
    image: "./img/aoe2.jpg",
  },
  {
    question: "What is the name of the protagonist in the Halo game series?",
    answer1: "Cortana",
    answer2: "Masterchief 117",
    answer3: "Solid Snake",
    answer4: "Link",
    right_answer: 2,
    image: "./img/masterchief117.jpg",
  },
  {
    question: "Which game is considered the forefather of video games?",
    answer1: "Tetris",
    answer2: "Zelda The Ocarina of Time",
    answer3: "Super Mario Bros",
    answer4: "Pong",
    right_answer: 4,
    image: "./img/pong.png",
  },
  {
    question: "In which year was World of Warcraft released?",
    answer1: "1998",
    answer2: "2004",
    answer3: "2018",
    answer4: "2009",
    right_answer: 2,
    image: "./img/wow.jpg",
  },
  {
    question: "What is the name of the green dinosaur from the Mario games?",
    answer1: "Yoshi",
    answer2: "Shrek",
    answer3: "Mike Wazowski",
    answer4: "Bowser",
    right_answer: 1,
    image: "./img/yoshi.jpg",
  },
  {
    question:
      "What is the name of the handheld console that was released in 1989?",
    answer1: "Gamecube",
    answer2: "Playstation Portable",
    answer3: "Nintendo DS",
    answer4: "Gameboy",
    right_answer: 4,
    image: "./img/gameboy.jpg",
  },
  {
    question: "What game series does Claptrap come from?",
    answer1: "The Elder Scrolls",
    answer2: "Diablo",
    answer3: "Borderlands",
    answer4: "Fallout",
    right_answer: 3,
    image: "./img/claptrap.jpeg",
  },
  {
    question: "As of 2023, which game has the most unique players per month?",
    answer1: "Counterstrike GO",
    answer2: "League of Legends",
    answer3: "Hearthstone",
    answer4: "Dota2",
    right_answer: 2,
    image: "./img/lol.webp",
  },
  {
    question: "Which game revolutionized the open world genre?",
    answer1: "Grand Theft Auto 3",
    answer2: "Spyro 3 Year of the Dragon",
    answer3: "God of War II ",
    answer4: "Prince of Persia 2 The Shadow & The Flame",
    right_answer: 1,
    image: "./img/gta3.jpg",
  },
];
